In [1]:
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [ ]:
%run Kcond.ipynb

Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib


KeyboardInterrupt: 

/Users/michellemadin/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2542: UserWarning: Unknown failure executing file: </Users/michellemadin/Documents/Imperial/UROP/Ocean Speciation Project/Python SHIAMI/Kthermo.ipynb>
  warn('Unknown failure executing file: <%s>' % fname)


Populating the interactive namespace from numpy and matplotlib
[[ 1.43783204e+01  5.60767400e-03 -4.22185236e+02 -2.51226677e+00
   0.00000000e+00 -2.61718135e-06  4.43854508e+00 -1.70502337e+00]
 [-4.83060685e-01  1.40677470e-03  1.19311989e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.23433299e+00]
 [-1.00588714e-01 -1.80529413e-05  8.61185543e+00  1.24880950e-02
   0.00000000e+00  3.41172108e-08  6.83040995e-02  2.93922611e-01]]
[-1.3764e+01  1.2121e-01 -2.7642e-04  0.0000e+00 -2.1515e-01 -3.2743e+01]
Populating the interactive namespace from numpy and matplotlib
[[ 0.          0.51062135  0.07        0.05        0.07      ]
 [ 0.51062135  0.          0.          0.1156      0.01      ]
 [ 0.07        0.          0.          0.007       0.        ]
 [ 0.05        0.1156      0.007       0.          0.        ]
 [ 0.07        0.01        0.          0.          0.        ]
 [ 0.09124835  0.06714162 -0.02745662 -0.02825662 -0.0638175 ]
 [ 0.          0.     

[[ 1.43783204e+01  5.60767400e-03 -4.22185236e+02 -2.51226677e+00
   0.00000000e+00 -2.61718135e-06  4.43854508e+00 -1.70502337e+00]
 [-4.83060685e-01  1.40677470e-03  1.19311989e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.23433299e+00]
 [-1.00588714e-01 -1.80529413e-05  8.61185543e+00  1.24880950e-02
   0.00000000e+00  3.41172108e-08  6.83040995e-02  2.93922611e-01]]
[-1.3764e+01  1.2121e-01 -2.7642e-04  0.0000e+00 -2.1515e-01 -3.2743e+01]
[[-1.04419906e+01 -5.67174834e+01 -2.02702896e+00 ... -4.56057000e+01
  -6.33375600e+01  1.42600000e-01]
 [-1.85012170e+01 -3.74507973e+01 -5.52180705e-01 ...  0.00000000e+00
   0.00000000e+00  1.58700000e-01]
 [ 5.53145847e-01 -1.91983514e+02  0.00000000e+00 ...  3.50000000e-01
  -2.80000000e+00  0.00000000e+00]
 ...
 [ 8.25400000e-01  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.12000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+

ValueError: Expected 1D or 2D array, got 0D array instead

NameError: name 'Kthermo' is not defined

Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
[[1.75754254e-01 5.01187234e+00 1.86208714e+01 5.62341325e-01
  4.67339067e-02 1.06959380e-01 1.65958691e+00 6.60693448e-01]
 [3.35809321e-02 7.02642685e+00 0.00000000e+00 0.00000000e+00
  1.90239911e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.80694708e-01 2.67043780e+02 9.54246334e+02 1.16141564e+01
  0.00000000e+00 6.60693448e+01 3.71535229e+01 1.54037108e+02]
 [2.11952224e-01 1.99526231e+02 1.67529331e+03 1.18501483e+01
  0.00000000e+00 8.70963590e+00 6.30957344e+01 1.99526231e+01]
 [5.93934636e-01 1.94984460e+02 1.00087885e+03 1.52966401e+01
  0.00000000e+00 1.46150249e+00 3.54813389e+01 6.60693448e+00]]
[[[0.00000000e+00 1.37891811e-01 0.00000000e+00 0.00000000e+00
   0.00000000e+00 6.70529362e-04 0.00000000e+00]
  [3.28072669e-02 5.01187234e+00 0.00000000e+00 0.00000000e+00
   0.00000000e+00 2.04173794e+00 0.00000000e+00]
  [1.14190202e-01 8.7096

[[1.75754254e-01 5.01187234e+00 1.86208714e+01 5.62341325e-01
  4.67339067e-02 1.06959380e-01 1.65958691e+00 6.60693448e-01]
 [3.35809321e-02 7.02642685e+00 0.00000000e+00 0.00000000e+00
  1.90239911e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.80694708e-01 2.67043780e+02 9.54246334e+02 1.16141564e+01
  0.00000000e+00 6.60693448e+01 3.71535229e+01 1.54037108e+02]
 [2.11952224e-01 1.99526231e+02 1.67529331e+03 1.18501483e+01
  0.00000000e+00 8.70963590e+00 6.30957344e+01 1.99526231e+01]
 [5.93934636e-01 1.94984460e+02 1.00087885e+03 1.52966401e+01
  0.00000000e+00 1.46150249e+00 3.54813389e+01 6.60693448e+00]]
[[[0.00000000e+00 1.37891811e-01 0.00000000e+00 0.00000000e+00
   0.00000000e+00 6.70529362e-04 0.00000000e+00]
  [3.28072669e-02 5.01187234e+00 0.00000000e+00 0.00000000e+00
   0.00000000e+00 2.04173794e+00 0.00000000e+00]
  [1.14190202e-01 8.70963590e+00 0.00000000e+00 0.00000000e+00
   6.32337296e-02 9.53049158e+00 0.00000000e+00]
  [7.58158215e-01 1.09647820e+01 5.128

[[ 1.43783204e+01  5.60767400e-03 -4.22185236e+02 -2.51226677e+00
   0.00000000e+00 -2.61718135e-06  4.43854508e+00 -1.70502337e+00]
 [-4.83060685e-01  1.40677470e-03  1.19311989e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.23433299e+00]
 [-1.00588714e-01 -1.80529413e-05  8.61185543e+00  1.24880950e-02
   0.00000000e+00  3.41172108e-08  6.83040995e-02  2.93922611e-01]]
[-1.3764e+01  1.2121e-01 -2.7642e-04  0.0000e+00 -2.1515e-01 -3.2743e+01]
Populating the interactive namespace from numpy and matplotlib
[[ 0.          0.51062135  0.07        0.05        0.07      ]
 [ 0.51062135  0.          0.          0.1156      0.01      ]
 [ 0.07        0.          0.          0.007       0.        ]
 [ 0.05        0.1156      0.007       0.          0.        ]
 [ 0.07        0.01        0.          0.          0.        ]
 [ 0.09124835  0.06714162 -0.02745662 -0.02825662 -0.0638175 ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.     

[[ 1.43783204e+01  5.60767400e-03 -4.22185236e+02 -2.51226677e+00
   0.00000000e+00 -2.61718135e-06  4.43854508e+00 -1.70502337e+00]
 [-4.83060685e-01  1.40677470e-03  1.19311989e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.23433299e+00]
 [-1.00588714e-01 -1.80529413e-05  8.61185543e+00  1.24880950e-02
   0.00000000e+00  3.41172108e-08  6.83040995e-02  2.93922611e-01]]
[-1.3764e+01  1.2121e-01 -2.7642e-04  0.0000e+00 -2.1515e-01 -3.2743e+01]
[[-1.04419906e+01 -5.67174834e+01 -2.02702896e+00 ... -4.56057000e+01
  -6.33375600e+01  1.42600000e-01]
 [-1.85012170e+01 -3.74507973e+01 -5.52180705e-01 ...  0.00000000e+00
   0.00000000e+00  1.58700000e-01]
 [ 5.53145847e-01 -1.91983514e+02  0.00000000e+00 ...  3.50000000e-01
  -2.80000000e+00  0.00000000e+00]
 ...
 [ 8.25400000e-01  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.12000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+

ValueError: Expected 1D or 2D array, got 0D array instead

[[6.13834426e-01 5.80717464e-01 1.85335228e-01 1.78824768e-01
  1.74704322e-01 6.99975028e-01 6.74752887e-01 5.61099256e-01
  5.17602103e-01 5.69753080e-01 1.53235031e-01 1.71530179e-01
  1.60694113e-01 1.61929393e-01 1.64838332e-01 1.43047060e-01
  1.58707894e-01 1.87727793e-01 6.19960046e-02 7.29811864e-02
  6.81858212e-02 5.93129134e-01 2.65711399e-02 2.80149327e-02
  2.75762966e-02 2.74778270e-02 2.75762966e-02 2.79057636e-02
  2.81391910e-02 2.81980720e-02 2.83879926e-02 2.85144095e-02
  2.86966334e-02 2.85173147e-02 2.84755433e-02 2.84245219e-02
  2.84095522e-02 2.86857790e-02 3.42804857e-02 5.12833788e-02
  1.87928283e-04 3.41796667e-02]]
[[0.65490785 0.10861439 0.09606881 0.56564255 0.67540064 0.65503125
  0.38403465 0.54115857 0.74768361 0.64886902 0.71250284 0.61460225
  0.65887841 0.57846595 0.6833468  0.60787998 0.59614753 0.59039397
  0.08131462 0.003992   0.74895271 0.11984497 0.00826993 0.69796704
  0.10015788 0.0737283 ]]
[[0.83380972 0.54227923 0.61819832 0.095      0.

[[1.00135665 1.00726213 1.07986777 1.11417281 1.03616092 1.01037069
  1.13323512]]


NameError: name 'Tc' is not defined

[[1.01037069 0.67540064 0.67540064 1.01037069 1.01037069 1.01037069
  1.01037069 1.01037069]
 [1.01037069 0.67540064 1.         1.         1.01037069 1.
  1.         1.01037069]
 [0.76019625 1.         1.         0.76019625 1.         0.54227923
  0.76019625 0.83380972]
 [0.76019625 1.         1.         0.76019625 1.         0.61819832
  0.76019625 0.76019625]
 [0.76019625 1.         1.         0.76019625 1.         0.76019625
  0.76019625 0.76019625]]
[[[0.         0.74768361 0.         0.         0.         1.01037069
   0.        ]
  [1.01037069 0.67540064 0.         0.         0.         1.01037069
   0.        ]
  [1.01037069 0.67540064 0.         0.         1.01037069 1.01037069
   0.        ]
  [1.01037069 0.67540064 0.67540064 0.         1.01037069 0.
   0.        ]
  [0.         0.67540064 0.         0.         0.         0.
   0.        ]
  [0.76019625 1.         1.         0.76019625 0.         0.76019625
   0.        ]
  [0.095      0.         0.         0.         0.     

[[6.99288753e-02 4.94740122e-01 1.62581892e+00 1.93246918e-01
  1.91762666e-02 4.25648784e-02 3.87204963e-01 2.17217617e-01]
 [1.26402915e-02 6.56183502e-01 0.00000000e+00 0.00000000e+00
  7.38494477e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.24650402e-01 5.37561060e+00 1.69902933e+01 1.60162927e+00
  0.00000000e+00 1.47909824e+01 3.47858537e+00 1.85285280e+01]
 [3.26527770e-02 3.87538657e+00 2.87806716e+01 1.57676803e+00
  0.00000000e+00 1.65029607e+00 5.69996725e+00 2.53995773e+00]
 [8.93916134e-02 3.69990872e+00 1.67983862e+01 1.98845630e+00
  0.00000000e+00 2.20008524e-01 3.13147061e+00 8.21679534e-01]]
[[[0.00000000e+00 1.40213723e-02 0.00000000e+00 0.00000000e+00
   0.00000000e+00 3.04285758e-04 0.00000000e+00]
  [1.43487563e-02 5.43839367e-01 0.00000000e+00 0.00000000e+00
   0.00000000e+00 8.93153348e-01 0.00000000e+00]
  [4.15305793e-02 7.85896914e-01 0.00000000e+00 0.00000000e+00
   2.37175170e-02 3.46685976e+00 0.00000000e+00]
  [2.54363817e-01 9.12687122e-01 3.775

In [ ]:
%run guess_alphaV3.ipynb

Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
[[1.75754254e-01 5.01187234e+00 1.86208714e+01 5.62341325e-01
  4.67339067e-02 1.06959380e-01 1.65958691e+00 6.60693448e-01]
 [3.35809321e-02 7.02642685e+00 0.00000000e+00 0.00000000e+00
  1.90239911e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.80694708e-01 2.67043780e+02 9.54246334e+02 1.16141564e+01
  0.00000000e+00 6.60693448e+01 3.71535229e+01 1.54037108e+02]
 [2.11952224e-01 1.99526231e+02 1.67529331e+03 1.18501483e+01
  0.00000000e+00 8.70963590e+00 6.30957344e+01 1.99526231e+01]
 [5.93934636e-01 1.94984460e+02 1.00087885e+03 1.52966401e+01
  0.00000000e+00 1.46150249e+00 3.54813389e+01 6.60693448e+00]]
[[[0.00000000e+00 1.37891811e-01 0.00000000e+00 0.00000000e

[[ 1.43783204e+01  5.60767400e-03 -4.22185236e+02 -2.51226677e+00
   0.00000000e+00 -2.61718135e-06  4.43854508e+00 -1.70502337e+00]
 [-4.83060685e-01  1.40677470e-03  1.19311989e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.23433299e+00]
 [-1.00588714e-01 -1.80529413e-05  8.61185543e+00  1.24880950e-02
   0.00000000e+00  3.41172108e-08  6.83040995e-02  2.93922611e-01]]
[-1.3764e+01  1.2121e-01 -2.7642e-04  0.0000e+00 -2.1515e-01 -3.2743e+01]
Populating the interactive namespace from numpy and matplotlib
[[ 0.          0.51062135  0.07        0.05        0.07      ]
 [ 0.51062135  0.          0.          0.1156      0.01      ]
 [ 0.07        0.          0.          0.007       0.        ]
 [ 0.05        0.1156      0.007       0.          0.        ]
 [ 0.07        0.01        0.          0.          0.        ]
 [ 0.09124835  0.06714162 -0.02745662 -0.02825662 -0.0638175 ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.     

[[ 1.43783204e+01  5.60767400e-03 -4.22185236e+02 -2.51226677e+00
   0.00000000e+00 -2.61718135e-06  4.43854508e+00 -1.70502337e+00]
 [-4.83060685e-01  1.40677470e-03  1.19311989e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.23433299e+00]
 [-1.00588714e-01 -1.80529413e-05  8.61185543e+00  1.24880950e-02
   0.00000000e+00  3.41172108e-08  6.83040995e-02  2.93922611e-01]]
[-1.3764e+01  1.2121e-01 -2.7642e-04  0.0000e+00 -2.1515e-01 -3.2743e+01]
[[-1.04419906e+01 -5.67174834e+01 -2.02702896e+00 ... -4.56057000e+01
  -6.33375600e+01  1.42600000e-01]
 [-1.85012170e+01 -3.74507973e+01 -5.52180705e-01 ...  0.00000000e+00
   0.00000000e+00  1.58700000e-01]
 [ 5.53145847e-01 -1.91983514e+02  0.00000000e+00 ...  3.50000000e-01
  -2.80000000e+00  0.00000000e+00]
 ...
 [ 8.25400000e-01  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.12000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+

ValueError: Expected 1D or 2D array, got 0D array instead

[[6.13834426e-01 5.80717464e-01 1.85335228e-01 1.78824768e-01
  1.74704322e-01 6.99975028e-01 6.74752887e-01 5.61099256e-01
  5.17602103e-01 5.69753080e-01 1.53235031e-01 1.71530179e-01
  1.60694113e-01 1.61929393e-01 1.64838332e-01 1.43047060e-01
  1.58707894e-01 1.87727793e-01 6.19960046e-02 7.29811864e-02
  6.81858212e-02 5.93129134e-01 2.65711399e-02 2.80149327e-02
  2.75762966e-02 2.74778270e-02 2.75762966e-02 2.79057636e-02
  2.81391910e-02 2.81980720e-02 2.83879926e-02 2.85144095e-02
  2.86966334e-02 2.85173147e-02 2.84755433e-02 2.84245219e-02
  2.84095522e-02 2.86857790e-02 3.42804857e-02 5.12833788e-02
  1.87928283e-04 3.41796667e-02]]
[[0.65490785 0.10861439 0.09606881 0.56564255 0.67540064 0.65503125
  0.38403465 0.54115857 0.74768361 0.64886902 0.71250284 0.61460225
  0.65887841 0.57846595 0.6833468  0.60787998 0.59614753 0.59039397
  0.08131462 0.003992   0.74895271 0.11984497 0.00826993 0.69796704
  0.10015788 0.0737283 ]]
[[0.83380972 0.54227923 0.61819832 0.095      0.

In [ ]:
# alphasV3       This function calculates the fraction of free ions in a
#                solution of fixed composition and ionic strength (given)
#                needed for correcting free activity coefficients for ion
#                complexation. 
#                    
#               [alpha_cat, alpha_an, iter] = alphasV3(mT_cat, mT_an)
#                     alpha_cat  .......... [M]f/[M]T
#                     alpha_an   .......... [X]f/[X]T
# 
#
#                Assumptions:
#                1) 1:1 complexes only. Higher order complexes ignored
#                2) Trivalents form strong hydroxyl complexes
#                3) Br/Cl- ion pairs weak therefore ignored
#                           AlphaCl = 1.0  or [Cl]f = [Cl]T
#                           AlphaBr = 1.0  or [Br]f = [Br]T
#                5) Assume K forms only KSO4- Complex
#                6) The speciation of minor components of seawater can be
#                   made without making any iterations, since minor components
#                   do not affect the speciation of the major componenents 
#                
#
#                NOTE: The model is only good as the K data inputed.          
#
#              Major Cations                  Minor Cations 
#              Na, K, Mg, Ca, Sr              H, Li, Rb, Cs, NH4, Ba, Mn, Fe(II), Co, Ni, Cu(II), Zn
#                                             UO2, Be, Cd, Pb(II), MgOH, (MgF),(CaF) Cu(I)
#                                
#                                             REE
#                                             La, Ce, Pr, Nd, Pm, Sm, Eu, Gd, Tb, Dy, Ho, Er, Tm, Yb, 
#                                             Lu, Y
#                               
#                                             Trivalent
#                                             Al, Ga, In, Fe(III)
#
#
#             Major Anions                    Minor Anion
#             Cl, SO4, CO3, HCO3              HSO4, HS, OH, I, ClO3, ClO4, BrO3, CNS, NO2, NO3,
#             Br, F, B(OH)4                   H2PO4, HPO4, PO4, H2AsO4, HAsO4, AsO4, HSO3, SO3, Acetate
#
#               
#             'For major cations, the calculations a made using an iterative process
#              For minor components of seawater, calculations can be made without making 
#              any iteration, since minor components do not affect the speciation Of the 
#              major component.'    .....  Millero, 2006       
#               

## ----------------------------------------------------------------------------
##  Assign values to global variables
mjCaMax = 5         #In python array goes 0,1,2,3,4,5,6, so mjCaMax must go to 7 to include the 6th variable
mnCaMax = 37
CaMax = mjCaMax + mnCaMax

mjAnMax = 7          #In python array goes 0,1,2,3,4,5,6,7,8 so mjCaMax must go to 8 to include the 7th variable
mnAnMax = 19
AnMax = mjAnMax + mnAnMax

NeutMax = 7

def alphasV3(Tc, I, mT_cat, mT_an, OH):
    
    ## Determine lengths of input vectors
    veclengths=[size(Tc), size(I), size(len(mT_cat)), size(len(mT_an))]
    maxr = max(veclengths)
    
    if len(unique(veclengths)) > 2:
        print('*** INPUT ERROR: Input vectors must all be of same length, or of length 1. ***')
        
## ----------------------------------------------------------------------------
    mjKcond, mnCat_Kcond, divKcond, trivKcond  = Kcond(Tc, I, mT_cat,mT_an)
    alpha_cat2 = np.zeros([maxr,CaMax])
    alpha_an2  = np.zeros([maxr,AnMax])
    mT_an.append(OH)      # 10^(-14+pH)   

## MAJOR CAT-AN
## Iteration until convergence      

    alpha_cat2[0][0:5] = 1              # Initialize iteration by setting all alpha_cat = 1 
    alpha_an2[0][0:8] = 1               # Initialize iteration by setting all alpha_an = 1  

    itera = 2    
    error1 = 1
    error2 = 1
    tolerance = 0.00001

    alpha_an1, alpha_cat1 = guess_alphaV3(alpha_an2, alpha_cat2, mT_cat, mT_an, mjKcond, maxr)

    saa1 = sum(any(abs(error1 > tolerance)))
    saa2 = sum(any(abs(error2 > tolerance)))

    if saa1 > 0 or saa2 > 0:
        alpha_an, alpha_cat = guess_alphaV3(alpha_an1, alpha_cat1, mT_cat, mT_an, mjKcond, maxr)
        error1 = alpha_cat - alpha_cat1
        error2 = alpha_an - alpha_an1
        while itera < 9:
            itera = itera + 2
            
    mF_an = alpha_an[0][0:8]* mT_an
    mF_cat = alpha_cat[0][0:5]* mT_cat
    
    ## Minor Cations
    Lig = np.zeros([1,7])
    Lig = [1,2,3,4,5,6,8]           #[Cl, SO4, CO3, HCO3, Br, F, OH]

    A = np.zeros([maxr,7])
    for i in range(maxr,maxr+1):
        for II in range(7):
            for JJ in range(7):
                for KK in range(3):
                    if  mnCat_Kcond[KK, II, JJ] !=0:
                        A[0][II] = A[0][II] +  mnCat_Kcond[KK, II, JJ] * (mF_an[Lig[JJ]-1]**(KK+1))
                    
            
    alpha_cat[0][5:11] = 1/(A[0][0:6] + 1) 
    alpha_cat[:,21] = 1/(A[:,6] + 1)
                                                                      
    ## DIVALENTS 
    L = np.zeros([1,6])
    L = [1,2,3,4,6,8]             # [Cl, SO4, CO3, HCO3, F, OH]

    B = np.zeros([maxr,10])
    for i in range(maxr,maxr+1): 
        for II in range(10):
            for JJ in range(6):
                for KK in range(4):
                    B[0][II] = B[0][II] + divKcond[KK, II, JJ] * (mF_an[L[JJ]-1]**(KK+1))   
                

    alpha_cat[0][11:21] = 1/(B + 1) 

    ## TRIVALENT
    
    C = np.zeros([maxr,20])
    for i in range(maxr,maxr+1):
        for II in range(20):
            for JJ in range(6):
                for KK in range(4):
                    C[0][II] = C[0][II] + trivKcond[KK, II, JJ] * (mF_an[Lig[JJ]-1]**(KK+1))

    alpha_cat[0][22:42] = 1/(C + 1)
    
    return alpha_cat, alpha_an, mF_an, mF_cat, itera



In [ ]:
a_cat, a_an, mF_an, mF_cat, itera = alphasV3(25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.1))
print(a_cat)

In [ ]:
a_cat, a_an, mF_an, mF_cat, itera = alphasV3(25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.1))
print(a_an)

In [ ]:
a_cat, a_an, mF_an, mF_cat, itera = alphasV3(25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.1))
print(mF_an)

In [ ]:
10**(-14+8.1)