In [ ]:
import math
import numpy as np
%pylab inline

In [ ]:
%run Kcond.ipynb

Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
[[ 1.43783204e+01  5.60767400e-03 -4.22185236e+02 -2.51226677e+00
   0.00000000e+00 -2.61718135e-06  4.43854508e+00 -1.70502337e+00]
 [-4.83060685e-01  1.40677470e-03  1.19311989e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.23433299e+00]
 [-1.00588714e-01 -1.80529413e-05  8.61185543e+00  1.24880950e-02
   0.00000000e+00  3.41172108e-08  6.83040995e-02  2.93922611e-01]]
[-1.3764e+01  1.2121e-01 -2.7642e-04  0.0000e+00 -2.1515e-01 -3.2743e+01]
Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib
[[1.75754254e-01 5.01187234e+00 1.86208714e+01 5.62341325e-01
  4.67339067e-02 1.06959380e-01 1.65958691e+00 6.60693448e-01]
 [3.35809321e-02 7.02642685e+00 0.00000000e+00 0.00000000e+00
  1.90239911e-02 0.00000

[[ 1.43783204e+01  5.60767400e-03 -4.22185236e+02 -2.51226677e+00
   0.00000000e+00 -2.61718135e-06  4.43854508e+00 -1.70502337e+00]
 [-4.83060685e-01  1.40677470e-03  1.19311989e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.23433299e+00]
 [-1.00588714e-01 -1.80529413e-05  8.61185543e+00  1.24880950e-02
   0.00000000e+00  3.41172108e-08  6.83040995e-02  2.93922611e-01]]
[-1.3764e+01  1.2121e-01 -2.7642e-04  0.0000e+00 -2.1515e-01 -3.2743e+01]
[[-1.04419906e+01 -5.67174834e+01 -2.02702896e+00 ... -4.56057000e+01
  -6.33375600e+01  1.42600000e-01]
 [-1.85012170e+01 -3.74507973e+01 -5.52180705e-01 ...  0.00000000e+00
   0.00000000e+00  1.58700000e-01]
 [ 5.53145847e-01 -1.91983514e+02  0.00000000e+00 ...  3.50000000e-01
  -2.80000000e+00  0.00000000e+00]
 ...
 [ 8.25400000e-01  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.12000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+

[[6.13834426e-01 5.80717464e-01 1.85335228e-01 1.78824768e-01
  1.74704322e-01 6.99975028e-01 6.74752887e-01 5.61099256e-01
  5.17602103e-01 5.69753080e-01 1.53235031e-01 1.71530179e-01
  1.60694113e-01 1.61929393e-01 1.64838332e-01 1.43047060e-01
  1.58707894e-01 1.87727793e-01 6.19960046e-02 7.29811864e-02
  6.81858212e-02 5.93129134e-01 2.65711399e-02 2.80149327e-02
  2.75762966e-02 2.74778270e-02 2.75762966e-02 2.79057636e-02
  2.81391910e-02 2.81980720e-02 2.83879926e-02 2.85144095e-02
  2.86966334e-02 2.85173147e-02 2.84755433e-02 2.84245219e-02
  2.84095522e-02 2.86857790e-02 3.42804857e-02 5.12833788e-02
  1.87928283e-04 3.41796667e-02]]
[[0.65490785 0.10861439 0.09606881 0.56564255 0.67540064 0.65503125
  0.38403465 0.54115857 0.74768361 0.64886902 0.71250284 0.61460225
  0.65887841 0.57846595 0.6833468  0.60787998 0.59614753 0.59039397
  0.08131462 0.003992   0.74895271 0.11984497 0.00826993 0.69796704
  0.10015788 0.0737283 ]]
[[0.83380972 0.54227923 0.61819832 0.095      0.

[[1.75754254e-01 5.01187234e+00 1.86208714e+01 5.62341325e-01
  4.67339067e-02 1.06959380e-01 1.65958691e+00 6.60693448e-01]
 [3.35809321e-02 7.02642685e+00 0.00000000e+00 0.00000000e+00
  1.90239911e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.80694708e-01 2.67043780e+02 9.54246334e+02 1.16141564e+01
  0.00000000e+00 6.60693448e+01 3.71535229e+01 1.54037108e+02]
 [2.11952224e-01 1.99526231e+02 1.67529331e+03 1.18501483e+01
  0.00000000e+00 8.70963590e+00 6.30957344e+01 1.99526231e+01]
 [5.93934636e-01 1.94984460e+02 1.00087885e+03 1.52966401e+01
  0.00000000e+00 1.46150249e+00 3.54813389e+01 6.60693448e+00]]
[[[0.00000000e+00 1.37891811e-01 0.00000000e+00 0.00000000e+00
   0.00000000e+00 6.70529362e-04 0.00000000e+00]
  [3.28072669e-02 5.01187234e+00 0.00000000e+00 0.00000000e+00
   0.00000000e+00 2.04173794e+00 0.00000000e+00]
  [1.14190202e-01 8.70963590e+00 0.00000000e+00 0.00000000e+00
   6.32337296e-02 9.53049158e+00 0.00000000e+00]
  [7.58158215e-01 1.09647820e+01 5.128

[[ 1.43783204e+01  5.60767400e-03 -4.22185236e+02 -2.51226677e+00
   0.00000000e+00 -2.61718135e-06  4.43854508e+00 -1.70502337e+00]
 [-4.83060685e-01  1.40677470e-03  1.19311989e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.23433299e+00]
 [-1.00588714e-01 -1.80529413e-05  8.61185543e+00  1.24880950e-02
   0.00000000e+00  3.41172108e-08  6.83040995e-02  2.93922611e-01]]
[-1.3764e+01  1.2121e-01 -2.7642e-04  0.0000e+00 -2.1515e-01 -3.2743e+01]
Populating the interactive namespace from numpy and matplotlib
Populating the interactive namespace from numpy and matplotlib


In [ ]:
%run alphaV3.ipynb

In [ ]:
##  Assign values to global variables
mjCaMax = 5         #In python array goes 0,1,2,3,4,5,6, so mjCaMax must go to 7 to include the 6th variable
mnCaMax = 37
CaMax = mjCaMax + mnCaMax

mjAnMax = 7         #In python array goes 0,1,2,3,4,5,6,7,8 so mjCaMax must go to 8 to include the 7th variable
mnAnMax = 19
AnMax = mjAnMax + mnAnMax

NeutMax = 7

## --------------------------------------------------------------------------------------
def speciation (Tc, I, mT_cat, mT_an, OH):
    
    alpha_cat, alpha_an, mF_an, mF_cat, itera  = alphasV3(Tc, I, mT_cat,mT_an, OH)    
    mjKcond, mnCat_Kcond, divKcond, trivKcond  = Kcond(Tc, I, mT_cat,mT_an)

    ## Determine lengths of input vectors   
    veclengths=[size(Tc), size(I), size(len(mT_cat)), size(len(mT_an))]
    maxr = max(veclengths)
    
    if len(unique(veclengths)) > 2:
        print('*** INPUT ERROR: Input vectors must all be of same length, or of length 1. ***')
    
    ## Major cation speciation 
    mjcat_spec = np.zeros([maxr*mjCaMax,8])

    for i in range(maxr,maxr+1):
        for cat in range(5):
            for an in range(8):
                mjcat_spec [cat,an] = mjKcond[cat, an]* mF_an[an]* alpha_cat[:,cat]
                          
    sz = [1,maxr*mjCaMax]
    A = reshape(alpha_cat[0][0:5],sz)
    mjcat_FREE = A * 100
    # mjcat_percent = mjcat_spec * 100
      
    ## major anion speciation  
    mjan_spec = np.zeros([8,maxr*mjCaMax])     
    
    for an in range(8):
        for cat in range(5):
            mjan_spec [an,cat] = mjKcond[cat,an]* mF_cat[cat]* alpha_an[:,an]
                
    sz = [1,8]
    B = reshape(alpha_an[0][0:8],sz)
    mjan_FREE = B * 100
    # mjan_percent =   mjan_spec * 100
                
    ## Minor Cations
    Lig = np.zeros([1,7])
    Lig = [1,2,3,4,5,6,8]           #[Cl, SO4, CO3, HCO3, Br, F, OH]
    
    C = np.zeros([1,7])
    C = [6,7,8,9,10,11,22]          #[Li, Rb, Cs, NH4, Ba, Mn, La]

    mncat_spec = np.zeros([3,7,7])
                
    for II in range(7):
        for JJ in range(7):
            for KK in range(3):
                if mnCat_Kcond[KK, II, JJ] !=0: 
                    mncat_spec[KK, II, JJ] =  mnCat_Kcond[KK, II, JJ] * (mF_an[Lig[JJ]-1]**(KK+1)) * alpha_cat[0][C[II]-1]

    D = np.zeros([1,maxr*7])
    D[0][0:6] = alpha_cat[0][5:11]
    D[:,6] = alpha_cat[:,21]        
    mncat_FREE = D * 100
    # mncat_percent =  mncat_spec * 100
    
    ## DIVALENTS 
    L = np.zeros([1,6])
    L = [1,2,3,4,6,8]               # [Cl, SO4, CO3, HCO3, F, OH]                       
    
    div_spec = np.zeros([4,10,6])    
    
    for II in range(10):
        for JJ in range(6):
            for KK in range(4):
                if divKcond[KK, II, JJ] != 0:
                    div_spec [KK, II, JJ] = divKcond[KK, II, JJ] * (mF_an[L[JJ]-1]**(KK+1)) * alpha_cat[0][11+II]
    
    sz = [1,10*maxr]
    E = reshape(alpha_cat[0][11:21], sz)
    div_FREE = E * 100
    # div_percent = div_spec * 100
    
    ## TRIVALENT
    triv_spec = np.zeros([4, 20, 6])
                
    for II in range(20):
        for JJ in range(6):
            for KK in range(4):
                if trivKcond[KK, II, JJ] != 0:
                    triv_spec [KK, II, JJ] = trivKcond[KK, II, JJ] * (mF_an[L[JJ]-1]**(KK+1)) * alpha_cat[0][22+II]

    sz = [1,20]
    F = reshape(alpha_cat[0][22:42],sz)
    triv_FREE = F * 100
    # triv_percent =  triv_spec *100
                
    return mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE
                                                                                          

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('mjcat_spec_pH8p2.npy',mjcat_spec)
print(mjcat_spec)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('mjcat_FREE_pH8p2.npy',mjcat_FREE)
print(mjcat_FREE)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('mjan_spec_pH8p2.npy',mjan_spec)
print(mjan_spec)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('mjan_FREE_pH8p2.npy',mjan_FREE)
print(mjan_FREE)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('mncat_spec_pH8p2.npy',mncat_spec)
print(mncat_spec)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('mncat_FREE_pH8p2.npy',mncat_FREE)
print(mncat_FREE)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('div_spec_pH8p2.npy',div_spec)
print(div_spec)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('div_FREE_pH8p2.npy',div_FREE)
print(div_FREE)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('triv_spec_pH8p2.npy',triv_spec)
print(triv_spec)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 10**(-14+8.2))
#np.save('triv_FREE_pH8p2.npy',triv_FREE)
print(triv_FREE)

In [ ]:
mjcat_spec, mjcat_FREE, mjan_spec, mjan_FREE, mncat_spec, mncat_FREE, div_spec, div_FREE, triv_spec_false, triv_FREE = speciation (25, 0.7228, [0.4689674, 0.0102077, 0.0528171, 0.0102821, 0.0000907], [0.5458696, 0.0282352, 0.00024694, 0.00179143, 0.0008421, 0.0000683, 0.0001008], 7.75506018018797e-06)
print(triv_spec_false)